.TH "src/senergy/console.h" 3 "Tue Feb 25 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/console.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Console\fP"
.br
.RI "\fIContains replacements for 'printf' that use C++11 features, such as variadic templates\&. The printf replacement in this class is more C++ like, and for example supports standard strings, as oppossed to printf, which only supports C99 data types\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
