.TH "src/senergy/convert.h" 3 "Tue Jan 28 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/convert.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <ctgmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Convert\fP"
.br
.RI "\fIA simple conversion class, which simplifies conversion between various native data types\&. Based on the idea of the '\fBConvert\fP' class in the \&.NET framework\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
