.TH "DNS_HEADER" 3 "Tue Jan 28 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DNS_HEADER \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBid\fP"
.br
.ti -1c
.RI "unsigned char \fBrd\fP:1"
.br
.ti -1c
.RI "unsigned char \fBtc\fP:1"
.br
.ti -1c
.RI "unsigned char \fBaa\fP:1"
.br
.ti -1c
.RI "unsigned char \fBopcode\fP:4"
.br
.ti -1c
.RI "unsigned char \fBqr\fP:1"
.br
.ti -1c
.RI "unsigned char \fBrcode\fP:4"
.br
.ti -1c
.RI "unsigned char \fBcd\fP:1"
.br
.ti -1c
.RI "unsigned char \fBad\fP:1"
.br
.ti -1c
.RI "unsigned char \fBz\fP:1"
.br
.ti -1c
.RI "unsigned char \fBra\fP:1"
.br
.ti -1c
.RI "unsigned short \fBq_count\fP"
.br
.ti -1c
.RI "unsigned short \fBans_count\fP"
.br
.ti -1c
.RI "unsigned short \fBauth_count\fP"
.br
.ti -1c
.RI "unsigned short \fBadd_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file main\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char DNS_HEADER::aa"

.PP
Definition at line 30 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::ad"

.PP
Definition at line 35 of file main\&.cpp\&.
.SS "unsigned short DNS_HEADER::add_count"

.PP
Definition at line 41 of file main\&.cpp\&.
.SS "unsigned short DNS_HEADER::ans_count"

.PP
Definition at line 39 of file main\&.cpp\&.
.SS "unsigned short DNS_HEADER::auth_count"

.PP
Definition at line 40 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::cd"

.PP
Definition at line 34 of file main\&.cpp\&.
.SS "unsigned short DNS_HEADER::id"

.PP
Definition at line 27 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::opcode"

.PP
Definition at line 31 of file main\&.cpp\&.
.SS "unsigned short DNS_HEADER::q_count"

.PP
Definition at line 38 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::qr"

.PP
Definition at line 32 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::ra"

.PP
Definition at line 37 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::rcode"

.PP
Definition at line 33 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::rd"

.PP
Definition at line 28 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::tc"

.PP
Definition at line 29 of file main\&.cpp\&.
.SS "unsigned char DNS_HEADER::z"

.PP
Definition at line 36 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
