.TH "src/senergy/dns/id_factory.h" 3 "Tue Feb 25 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/id_factory.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <random>\fP
.br
\fC#include <senergy/circular_buffer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::IdFactory\fP"
.br
.RI "\fIStatic global factory that is used to generate random identifiers for DNS messages/packets\&. This is to ensure, each ID that is generated is unique\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
