.TH "src/senergy/dns/message_question.h" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/message_question.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <senergy/bytebuffer\&.h>\fP
.br
\fC#include <senergy/convert\&.h>\fP
.br
\fC#include <senergy/vectorx\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_types\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_classes\&.h>\fP
.br
\fC#include <senergy/dns/utils\&.h>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::MessageQuestion\fP"
.br
.RI "\fIRepresents a DNS question, as defined in section 4\&.1\&.2 of RFC-1035\&. A DNS question is usually transmitted by a DNS client, asking to lookup the IP address of a host name\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr
.br
< MessageQuestion > \fBSenergy::Dns::MessageQuestionPtr\fP"
.br
.RI "\fISimple shared pointer to a MessageQuestionPtr instance\&. \fP"
.ti -1c
.RI "typedef VectorX
.br
< MessageQuestionPtr > \fBSenergy::Dns::MessageQuestionPtrVector\fP"
.br
.RI "\fIA vector of shared pointers to \fBMessageQuestion\fP instances\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
