.TH "src/senergy/dns/message.h" 3 "Wed Jan 29 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/message.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <senergy/dns/message_header\&.h>\fP
.br
\fC#include <senergy/dns/message_question\&.h>\fP
.br
\fC#include <senergy/bytebuffer\&.h>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::Message\fP"
.br
.RI "\fIRepresents a DNS packet as described in section 4 of RFC-1035\&. A DNS packet is the standard message format that is transmitted and received by DNS clients and hosts\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
