.TH "src/senergy/dns/record_ipv4address.h" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/record_ipv4address.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <senergy/dns/resource_record_types\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_classes\&.h>\fP
.br
\fC#include <senergy/dns/message_header\&.h>\fP
.br
\fC#include <senergy/dns/resource_record\&.h>\fP
.br
\fC#include <senergy/socket\&.h>\fP
.br
\fC#include <senergy/vectorx\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::Records::IPV4Address\fP"
.br
.RI "\fIAn address record, contains the answer to a lookup\&. Contains a IPV4 IP address, the response to a question, to lookup a hostname/domain name\&. This is part of a resource record, and the actual data is stored in the last field of a recource record (RDATE)\&. See the ResourceClass and section 3\&.4\&.1 of RFC 1035 for more information\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns::Records\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr
.br
< IPV4Address > \fBSenergy::Dns::Records::IPV4AddressPtr\fP"
.br
.RI "\fIA shared pointer to a \fBIPV4Address\fP instance\&. \fP"
.ti -1c
.RI "typedef VectorX< IPV4AddressPtr > \fBSenergy::Dns::Records::IPV4AddressPtrVector\fP"
.br
.RI "\fIA vector of shared pointers to \fBIPV4Address\fP instances\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
