.TH "src/senergy/dns/record_nameserver.h" 3 "Tue Feb 25 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/record_nameserver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <senergy/bytebuffer\&.h>\fP
.br
\fC#include <senergy/socket\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_types\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_interface\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_base\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::NameServerRecord\fP"
.br
.RI "\fIRepresents a DNS 'NS' record, which is a resource record that contains an nameserver address\&. It is what root DNS servers usually send back\&. This is defined in section 3\&.3\&.11 of RFC 1035\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
