.TH "references" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
references \- References 
An overview of websites, links, references and all kinds of sources of information\&.
.PP
.IP "\(bu" 2
http://www.zytrax.com/books/dns/ch15
.IP "\(bu" 2
http://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml
.IP "\(bu" 2
http://www.george-barwood.pwp.blueyonder.co.uk/DnsServer/
.IP "\(bu" 2
http://www.ietf.org/rfc/rfc1035.txt
.IP "\(bu" 2
http://www.binarytides.com/dns-query-code-in-c-with-winsock/
.IP "\(bu" 2
http://www.iana.org/domains/root/servers
.IP "\(bu" 2
http://www.iana.org/domains/root/files
.IP "\(bu" 2
http://tools.ietf.org/html/rfc2606
.IP "\(bu" 2
http://www.icann.org/en/resources/idn
.IP "\(bu" 2
http://tools.ietf.org/html/rfc3172
.IP "\(bu" 2
http://www.iana.org/domains/arpa
.IP "\(bu" 2
http://www.iana.org/domains/idn-tables
.IP "\(bu" 2
http://www.iana.org/domains/int
.IP "\(bu" 2
https://www.iana.org/dnssec 
.PP

