.TH "src/senergy/dns/requester.h" 3 "Tue Feb 4 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/requester.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <senergy/bytebuffer\&.h>\fP
.br
\fC#include <senergy/socket\&.h>\fP
.br
\fC#include <senergy/vectorx\&.h>\fP
.br
\fC#include <senergy/types\&.h>\fP
.br
\fC#include <senergy/dns/message\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::Requester\fP"
.br
.RI "\fIAllows querying remote DNS servers, wraps sending and receiving DNS messages\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
