.TH "src/senergy/dns/resource_record_classes.h" 3 "Tue Feb 25 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/resource_record_classes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSenergy::Dns::ResourceRecordClass\fP : unsigned short { \fBSenergy::Dns::ResourceRecordClass::Reserved\fP = 0, \fBSenergy::Dns::ResourceRecordClass::Internet\fP = 1, \fBSenergy::Dns::ResourceRecordClass::Chaos\fP = 2, \fBSenergy::Dns::ResourceRecordClass::Hesiod\fP = 3, \fBSenergy::Dns::ResourceRecordClass::None\fP = 254, \fBSenergy::Dns::ResourceRecordClass::Any\fP = 255 }"
.br
.RI "\fIAn enumuration of all possible resource record classes (RR) as defined in RFC-1035\&. None of them except 'Internet' are really used\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
