.TH "src/senergy/dns/resource_record.h" 3 "Sat Feb 1 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/resource_record.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <senergy/dns/resource_record_types\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_classes\&.h>\fP
.br
\fC#include <senergy/dns/utils\&.h>\fP
.br
\fC#include <senergy/bytebuffer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::ResourceRecord\fP"
.br
.RI "\fIDefines a DNS Resource Record, as defined in RFC 1035, section 4\&.1\&.3\&. A DNS Recource record can appear both in the answer, authority and additional section of a DNS packet/message\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
