.TH "src/senergy/dns/resource_record_collection.h" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/resource_record_collection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <senergy/dns/resource_record_types\&.h>\fP
.br
\fC#include <senergy/dns/resource_record_classes\&.h>\fP
.br
\fC#include <senergy/dns/resource_record\&.h>\fP
.br
\fC#include <senergy/dns/record_ipv4address\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::ResourceRecordCollection\fP"
.br
.RI "\fISimple container for all types of resource records we support\&. This is to prevent creating hundreds of separate containers in the \fBMessage\fP class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
