.TH "src/senergy/dns/rootnameserver.h" 3 "Sat Feb 1 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/dns/rootnameserver.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSenergy::Dns::RootNameServer\fP"
.br
.RI "\fIRepresents one of the 13 Root Name Servers (DNS) that are currently operating around the world\&. Provides access to the functionalities that root name servers offer\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.ti -1c
.RI "\fBSenergy::Dns\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
