.TH "Senergy" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBDns\fP"
.br
.ti -1c
.RI "\fBSocketError\fP"
.br
.RI "\fIDefines possible errors that can occur within the \fBSocket\fP class\&. \fP"
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBByteBuffer\fP"
.br
.RI "\fIA dynamiclly sized buffer for binary data\&. Resizes the underlying buffer when new data is written\&. Makes it easier to write to buffers that already contain data\&. \fP"
.ti -1c
.RI "class \fBCircularBuffer\fP"
.br
.RI "\fISimple circular buffer which uses a vector, simple circular buffer which should not be used in situations that require efficiency and power\&. \fP"
.ti -1c
.RI "class \fBConsole\fP"
.br
.ti -1c
.RI "class \fBConvert\fP"
.br
.RI "\fIA simple conversion class, which simplifies conversion between various native data types\&. Based on the idea of the '\fBConvert\fP' class in the \&.NET framework\&. \fP"
.ti -1c
.RI "class \fBLogger\fP"
.br
.RI "\fISimple logger with support for variadic arguments and various log levels\&. \fP"
.ti -1c
.RI "class \fBPrint\fP"
.br
.RI "\fIContains simple utilities that facilitate printing various data types or data structures to the screen\&. \fP"
.ti -1c
.RI "class \fBSocket\fP"
.br
.RI "\fIProvides an object-oriented interface for Berkely (BSD) sockets\&. Can act both as a server as well as a client\&. The main purpose of this class class is to provide a more C++ like interface for TCP sockets\&. \fP"
.ti -1c
.RI "class \fBVectorX\fP"
.br
.RI "\fIAn improvemend upon the standard vector (std::vector), but it's interface is more like the rest of \fBSenergy\fP (naming)\&. All normal functionality is still available, and switching between \fBVectorX\fP and std::vector should be painless\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr
.br
< \fBByteBuffer\fP > \fBByteBufferPtr\fP"
.br
.RI "\fIA simple typedef for a shared pointer to a \fBByteBuffer\fP instance\&. \fP"
.ti -1c
.RI "typedef std::shared_ptr< \fBSocket\fP > \fBSocketPtr\fP"
.br
.RI "\fIA simple typedef for the shared pointer of a TcpSocket instance\&. \fP"
.ti -1c
.RI "typedef \fBVectorX\fP< std::string > \fBStringVector\fP"
.br
.RI "\fIA std::vector of std::string objects\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLogLevel\fP { \fBLogLevel::Info\fP, \fBLogLevel::Error\fP, \fBLogLevel::Warning\fP, \fBLogLevel::Debug\fP }"
.br
.RI "\fIAn enumuration of all possible log levels, log levels will result in prefixes in log entries\&. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::shared_ptr<\fBByteBuffer\fP> \fBSenergy::ByteBufferPtr\fP"

.PP
A simple typedef for a shared pointer to a \fBByteBuffer\fP instance\&. 
.PP
Definition at line 471 of file bytebuffer\&.h\&.
.SS "typedef std::shared_ptr<\fBSocket\fP> \fBSenergy::SocketPtr\fP"

.PP
A simple typedef for the shared pointer of a TcpSocket instance\&. 
.PP
Definition at line 513 of file socket\&.h\&.
.SS "typedef \fBVectorX\fP<std::string> \fBSenergy::StringVector\fP"

.PP
A std::vector of std::string objects\&. 
.PP
Definition at line 35 of file types\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSenergy::LogLevel\fP\fC [strong]\fP"

.PP
An enumuration of all possible log levels, log levels will result in prefixes in log entries\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIInfo \fP\fP
.TP
\fB\fIError \fP\fP
.TP
\fB\fIWarning \fP\fP
.TP
\fB\fIDebug \fP\fP
.PP
Definition at line 40 of file logger\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
