.TH "Senergy::Convert" 3 "Tue Jan 28 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::Convert \- 
.PP
A simple conversion class, which simplifies conversion between various native data types\&. Based on the idea of the '\fBConvert\fP' class in the \&.NET framework\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <convert\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBToString\fP (int value)"
.br
.RI "\fIConverts the specified integer value to a string\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A simple conversion class, which simplifies conversion between various native data types\&. Based on the idea of the '\fBConvert\fP' class in the \&.NET framework\&. 


.PP
\fBAuthor:\fP
.RS 4
Swen Kooij (Photonios) 
.RE
.PP

.PP
Definition at line 40 of file convert\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string Senergy::Convert::ToString (intvalue)\fC [static]\fP"

.PP
Converts the specified integer value to a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The integer value to convert to a string\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The specified integer value as a string\&. 
.RE
.PP

.PP
Definition at line 27 of file convert\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
