.TH "Senergy::VectorX< T >" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::VectorX< T > \- 
.PP
An improvemend upon the standard vector (std::vector), but it's interface is more like the rest of \fBSenergy\fP (naming)\&. All normal functionality is still available, and switching between \fBVectorX\fP and std::vector should be painless\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vectorx\&.h>\fP
.PP
Inherits vector< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVectorX\fP ()"
.br
.RI "\fIInitializes a new, empty vector\&. \fP"
.ti -1c
.RI "T \fBAdd\fP (T value)"
.br
.RI "\fIAdds the specified item to the vector\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class Senergy::VectorX< T >"
An improvemend upon the standard vector (std::vector), but it's interface is more like the rest of \fBSenergy\fP (naming)\&. All normal functionality is still available, and switching between \fBVectorX\fP and std::vector should be painless\&. 

T The type that the vector will contain\&.
.PP
\fBAuthor:\fP
.RS 4
Swen Kooij (Photonios) 
.RE
.PP

.PP
Definition at line 40 of file vectorx\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBSenergy::VectorX\fP< T >::\fBVectorX\fP ()\fC [inline]\fP"

.PP
Initializes a new, empty vector\&. 
.PP
Definition at line 46 of file vectorx\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T> T \fBSenergy::VectorX\fP< T >::Add (Tvalue)\fC [inline]\fP"

.PP
Adds the specified item to the vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The object/value to add to the vector\&. 
.RE
.PP

.PP
Definition at line 55 of file vectorx\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
