.TH "Senergy" 3 "Tue Jan 28 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBNetworking\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBByteBuffer\fP"
.br
.RI "\fIA dynamiclly sized buffer for binary data\&. Resizes the underlying buffer when new data is written\&. Makes it easier to write to buffers that already contain data\&. \fP"
.ti -1c
.RI "class \fBConvert\fP"
.br
.RI "\fIA simple conversion class, which simplifies conversion between various native data types\&. Based on the idea of the '\fBConvert\fP' class in the \&.NET framework\&. \fP"
.ti -1c
.RI "class \fBPrint\fP"
.br
.RI "\fIContains simple utilities that facilitate printing various data types or data structures to the screen\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr
.br
< \fBByteBuffer\fP > \fBByteBufferPtr\fP"
.br
.RI "\fIA simple typedef for a shared pointer to a \fBByteBuffer\fP instance\&. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::shared_ptr<\fBByteBuffer\fP> \fBSenergy::ByteBufferPtr\fP"

.PP
A simple typedef for a shared pointer to a \fBByteBuffer\fP instance\&. 
.PP
Definition at line 349 of file bytebuffer\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
