.TH "Senergy::SocketError" 3 "Wed Jan 29 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::SocketError \- 
.PP
Defines possible errors that can occur within the \fBSocket\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBTimeout\fP = 9"
.br
.RI "\fIThrown when a socket operation (receing/binding/sending/connecting) times out\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines possible errors that can occur within the \fBSocket\fP class\&. 
.SH "Variable Documentation"
.PP 
.SS "const int Senergy::SocketError::Timeout = 9\fC [static]\fP"

.PP
Thrown when a socket operation (receing/binding/sending/connecting) times out\&. 
.PP
Definition at line 53 of file socket\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
