.TH "Senergy::Networking" 3 "Tue Jan 28 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::Networking \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocket\fP"
.br
.RI "\fIProvides an object-oriented interface for Berkely (BSD) sockets\&. Can act both as a server as well as a client\&. The main purpose of this class class is to provide a more C++ like interface for TCP sockets\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBSocket\fP > \fBSocketPtr\fP"
.br
.RI "\fIA simple typedef for the shared pointer of a TcpSocket instance\&. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::shared_ptr<\fBSocket\fP> \fBSenergy::Networking::SocketPtr\fP"

.PP
A simple typedef for the shared pointer of a TcpSocket instance\&. 
.PP
Definition at line 441 of file socket\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
