.TH "Senergy::Dns::Records" 3 "Tue Feb 4 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::Dns::Records \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIPV4Address\fP"
.br
.RI "\fIAn address record, contains the answer to a lookup\&. Contains a IPV4 IP address, the response to a question, to lookup a hostname/domain name\&. This is part of a resource record, and the actual data is stored in the last field of a recource record (RDATE)\&. See the ResourceClass and section 3\&.4\&.1 of RFC 1035 for more information\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
