.TH "Senergy::Dns::ResourceRecordCollection" 3 "Tue Feb 25 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::Dns::ResourceRecordCollection \- 
.PP
A collection of resource record\&. We have many types of resource record\&. \fBSenergy\fP DNS has a flexbile desing to simplify the implementation of additional records\&. This container is part of that design\&. It has the ability to contain all kinds of resource records\&. It also helps in serialization and deserialization\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resource_record_collection\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResourceRecordCollection\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBResourceRecordCollection\fP class\&. \fP"
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "\fIClears the collection of any existing records\&. \fP"
.ti -1c
.RI "bool \fBDeserialize\fP (\fBMessageHeader\fP &header, \fBByteBuffer\fP &buffer)"
.br
.RI "\fIDeserializes all resource records from the specified buffer, according to the information in the specified DNS message header\&. \fP"
.ti -1c
.RI "bool \fBSerialize\fP (\fBMessageHeader\fP &header, \fBByteBuffer\fP &buffer)"
.br
.RI "\fISerializeds all resource records from the specified buffer, according to the information in the specified DNS message header\&. \fP"
.ti -1c
.RI "void \fBDump\fP ()"
.br
.RI "\fIDumps the contents of this collection to the console\&. \fP"
.ti -1c
.RI "\fBVectorX\fP
.br
< \fBResourceRecordInterfacePtr\fP > & \fBoperator[]\fP (\fBResourceRecordType\fP resource_record_type)"
.br
.RI "\fIProvides access the resource records in this collection based on the specified resource record type\&. Returns all the resource records of the specified type\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A collection of resource record\&. We have many types of resource record\&. \fBSenergy\fP DNS has a flexbile desing to simplify the implementation of additional records\&. This container is part of that design\&. It has the ability to contain all kinds of resource records\&. It also helps in serialization and deserialization\&. 


.PP
\fBAuthor:\fP
.RS 4
Swen Kooij (Photonios) 
.RE
.PP

.PP
Definition at line 52 of file resource_record_collection\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Senergy::Dns::ResourceRecordCollection::ResourceRecordCollection ()"

.PP
Initializes a new instance of the \fBResourceRecordCollection\fP class\&. 
.PP
Definition at line 29 of file dns_resource_record_collection\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Senergy::Dns::ResourceRecordCollection::Clear ()"

.PP
Clears the collection of any existing records\&. 
.PP
Definition at line 36 of file dns_resource_record_collection\&.cpp\&.
.SS "bool Senergy::Dns::ResourceRecordCollection::Deserialize (\fBMessageHeader\fP &header, \fBByteBuffer\fP &buffer)"

.PP
Deserializes all resource records from the specified buffer, according to the information in the specified DNS message header\&. 
.PP
\fBNote:\fP
.RS 4
This clears this collection of all existing records\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIheader\fP The DNS message header to read the information on the amount of resource records from\&. 
.br
\fIbuffer\fP The buffer to read/deserialize the records from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A boolean indicating whether the deserialization was succesful\&. 
.RE
.PP

.PP
Definition at line 41 of file dns_resource_record_collection\&.cpp\&.
.SS "void Senergy::Dns::ResourceRecordCollection::Dump ()"

.PP
Dumps the contents of this collection to the console\&. 
.PP
Definition at line 88 of file dns_resource_record_collection\&.cpp\&.
.SS "\fBVectorX\fP<\fBResourceRecordInterfacePtr\fP>& Senergy::Dns::ResourceRecordCollection::operator[] (\fBResourceRecordType\fPresource_record_type)\fC [inline]\fP"

.PP
Provides access the resource records in this collection based on the specified resource record type\&. Returns all the resource records of the specified type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresource_record_type\fP A value from the ResourceRecordType enumuration which indicates which type of resource records to return\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A vector of resource records of the specified type, they are returned in their polymorphic form\&. 
.RE
.PP

.PP
Definition at line 110 of file resource_record_collection\&.h\&.
.SS "bool Senergy::Dns::ResourceRecordCollection::Serialize (\fBMessageHeader\fP &header, \fBByteBuffer\fP &buffer)"

.PP
Serializeds all resource records from the specified buffer, according to the information in the specified DNS message header\&. 
.PP
\fBParameters:\fP
.RS 4
\fIheader\fP The DNS message header to write the information on the amount of resource records to\&. 
.br
\fIbuffer\fP The buffer to write the serialized records to\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A boolean indicating whether the serialization was succesful\&. 
.RE
.PP

.PP
Definition at line 76 of file dns_resource_record_collection\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
