.TH "Senergy::Dns::Records::IPV4Address" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::Dns::Records::IPV4Address \- 
.PP
An address record, contains the answer to a lookup\&. Contains a IPV4 IP address, the response to a question, to lookup a hostname/domain name\&. This is part of a resource record, and the actual data is stored in the last field of a recource record (RDATE)\&. See the ResourceClass and section 3\&.4\&.1 of RFC 1035 for more information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <record_ipv4address\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIPV4Address\fP (\fBResourceRecordPtr\fP resource_record)"
.br
.RI "\fIInitializes a new instance of the \fBIPV4Address\fP class with the specified resource record\&. \fP"
.ti -1c
.RI "bool \fBDeserialize\fP (\fBByteBuffer\fP &buffer)"
.br
.RI "\fIDeserializes the RDATA part of this resource record, and does NOT deserialize the first part of the resource record\&. \fP"
.ti -1c
.RI "bool \fBSerialize\fP (\fBByteBuffer\fP &buffer)"
.br
.RI "\fISerializes the RDATA part of this resource record, and does NOT serialize the first part of the resource record\&. \fP"
.ti -1c
.RI "void \fBDump\fP ()"
.br
.RI "\fIDumps all fields to the standard output, with their values\&. In the following format: \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static IPV4AddressPtr \fBCreate\fP (\fBResourceRecordPtr\fP resource_record)"
.br
.RI "\fIInitializes a new instance of the \fBIPV4Address\fP class as a shared pointer\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An address record, contains the answer to a lookup\&. Contains a IPV4 IP address, the response to a question, to lookup a hostname/domain name\&. This is part of a resource record, and the actual data is stored in the last field of a recource record (RDATE)\&. See the ResourceClass and section 3\&.4\&.1 of RFC 1035 for more information\&. 


.PP
\fBNote:\fP
.RS 4
This is coupled with the \fBResourceRecordType::A\fP type\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Swen Kooij (Photonios) 
.RE
.PP

.PP
Definition at line 50 of file record_ipv4address\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Senergy::Dns::Records::IPV4Address::IPV4Address (\fBResourceRecordPtr\fPresource_record)"

.PP
Initializes a new instance of the \fBIPV4Address\fP class with the specified resource record\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresource_record\fP The resource record to use as a base for this instance\&. 
.RE
.PP

.PP
Definition at line 31 of file dns_record_ipv4address\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "IPV4AddressPtr Senergy::Dns::Records::IPV4Address::Create (\fBResourceRecordPtr\fPresource_record)\fC [static]\fP"

.PP
Initializes a new instance of the \fBIPV4Address\fP class as a shared pointer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresource_record\fP The resource record to use as a base for this instance\&. 
.RE
.PP

.PP
Definition at line 36 of file dns_record_ipv4address\&.cpp\&.
.SS "bool Senergy::Dns::Records::IPV4Address::Deserialize (\fBByteBuffer\fP &buffer)"

.PP
Deserializes the RDATA part of this resource record, and does NOT deserialize the first part of the resource record\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresource_record\fP The resource record to use as the base\&. 
.br
\fIbuffer\fP The buffer to read from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A boolean indicating whether this operation was a success\&. If the operation failed, false is returned\&. When the operation was a success, true is returned\&. 
.RE
.PP

.PP
Definition at line 41 of file dns_record_ipv4address\&.cpp\&.
.SS "void Senergy::Dns::Records::IPV4Address::Dump ()"

.PP
Dumps all fields to the standard output, with their values\&. In the following format: 
.PP
Definition at line 68 of file dns_record_ipv4address\&.cpp\&.
.SS "bool Senergy::Dns::Records::IPV4Address::Serialize (\fBByteBuffer\fP &buffer)"

.PP
Serializes the RDATA part of this resource record, and does NOT serialize the first part of the resource record\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresource_record\fP The resource record to use as the base\&. 
.br
\fIbuffer\fP The buffer to write to\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A boolean indicating whether this operation was a success\&. If the operation failed, false is returned\&. When the operation was a success, true is returned\&. 
.RE
.PP

.PP
Definition at line 61 of file dns_record_ipv4address\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
