.TH "Senergy::FastMapItem< TKey, TValue >" 3 "Tue Feb 25 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::FastMapItem< TKey, TValue > \- 
.PP
The structure that \fBFastMap\fP stores in it's vector, this emulates a std::map iterator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fastmap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TKey \fBfirst\fP"
.br
.ti -1c
.RI "TValue \fBsecond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class TKey, class TValue>struct Senergy::FastMapItem< TKey, TValue >"
The structure that \fBFastMap\fP stores in it's vector, this emulates a std::map iterator\&. 

TKey The data type of the key that is stored in the map\&.  TValue The data type of the value that is stored in the map\&.
.PP
\fBAuthor:\fP
.RS 4
Swen Kooij (Photonio) 
.RE
.PP

.PP
Definition at line 41 of file fastmap\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class TKey, class TValue> TKey \fBSenergy::FastMapItem\fP< TKey, TValue >::first"

.PP
Definition at line 43 of file fastmap\&.h\&.
.SS "template<class TKey, class TValue> TValue \fBSenergy::FastMapItem\fP< TKey, TValue >::second"

.PP
Definition at line 44 of file fastmap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
