.TH "Senergy::Dns::Message" 3 "Tue Jan 28 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::Dns::Message \- 
.PP
Represents a DNS packet as described in section 4 of RFC-1035\&. A DNS packet is the standard message format that is transmitted and received by DNS clients and hosts\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBMessage\fP class, with default values, without questions, answers, authorities and additionals\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents a DNS packet as described in section 4 of RFC-1035\&. A DNS packet is the standard message format that is transmitted and received by DNS clients and hosts\&. 


.PP
\fBAuthor:\fP
.RS 4
Swen Kooij (Photonios) 
.RE
.PP

.PP
Definition at line 36 of file message\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Senergy::Dns::Message::Message ()"

.PP
Initializes a new instance of the \fBMessage\fP class, with default values, without questions, answers, authorities and additionals\&. 
.PP
Definition at line 29 of file message\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
