.TH "Senergy::Dns::RootNameServer" 3 "Tue Feb 25 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Senergy::Dns::RootNameServer \- 
.PP
Represents one of the 13 Root Name Servers (DNS) that are currently operating around the world\&. Provides access to the functionalities that root name servers offer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rootnameserver\&.h>\fP
.SH "Detailed Description"
.PP 
Represents one of the 13 Root Name Servers (DNS) that are currently operating around the world\&. Provides access to the functionalities that root name servers offer\&. 


.PP
\fBAuthor:\fP
.RS 4
Swen Kooij (Photonios) 
.RE
.PP

.PP
Definition at line 36 of file rootnameserver\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
