.TH "terminology" 3 "Sat Feb 1 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminology \- Terminology 
This page contains an overview of terms that are not easy to understand, when you don't know the meaning of them\&. Normal terms, or at least terms assumed a 'technical' person understands is not documented here\&.
.PP
\fBTerm\fP \fBExplaination\fP 
.PP
FQDN Fully Qualified Domain Name 
.PP
Domain Label Typically this is the format that is used in the QNAME field of a question (3www6google3com) 
.PP
RR Resource Record, a record that can appear in the answer, authority and additional section of DNS packets\&. 
.PP
AAAA IPv6 
.PP
A IPv4  
