.TH "src/senergy/types.h" 3 "Tue Feb 11 2014" "Version 1.0" "Senergy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/senergy/types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <senergy/vectorx\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSenergy\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef VectorX< std::string > \fBSenergy::StringVector\fP"
.br
.RI "\fIA std::vector of std::string objects\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Senergy from the source code\&.
